#!/usr/bin/env python3
"""
Derive main_openradioss.k from main.k.

OpenRadioss reads LS-DYNA .k input natively, but only the subset of keywords
its dyna2rad reader maps to Radioss entities.  Everything changed here was
checked against the reader source
(OpenRadioss/reader/source/dyna2rad/dyna2rad/_private/*.cxx):

  kept, confirmed supported
    *CONTACT_ERODING_SINGLE_SURFACE  -> /INTER/TYPE7   (matched by substring
                                        in convertcontacts.cxx)
    *LOAD_BODY_Z                     -> /GRAV
    *LOAD_SHELL_SET                  -> /PLOAD
    *MAT_ADD_EROSION                 -> read in convertprops.cxx

  replaced
    *LOAD_BLAST_ENHANCED             -> NOT supported.  An OpenRadioss
                                        maintainer states blast and ALE
                                        LS-DYNA keywords are not read.
                                        Replaced by a *LOAD_SHELL_SET
                                        pressure pulse on the drone body.
    *MAT_CRUSHABLE_FOAM (063)        -> *MAT_PIECEWISE_LINEAR_PLASTICITY.
                                        063 appears in the reader's name map
                                        but its conversion is unverified, and
                                        a soft 024 behaves close enough for a
                                        battery pack that is being crushed.
    glass *MAT_ELASTIC + erosion     -> brittle *MAT_PIECEWISE_LINEAR_PLASTICITY.
                                        convertprops.cxx only picks a failure
                                        thickness out of *MAT_ADD_EROSION, so
                                        the SIGP1 max-principal-stress
                                        criterion would silently be lost.

Run:  python3 make_openradioss.py
"""

import os

HERE = os.path.dirname(os.path.abspath(__file__))
src = open(os.path.join(HERE, "main.k")).read()


def sub(old, new, label):
    global src
    if old not in src:
        raise SystemExit("make_openradioss.py: pattern not found -> " + label)
    src = src.replace(old, new, 1)


# ---------------------------------------------------------------- header ----
sub("""$#=============================================================================
$# DRONE HIGH-SPEED IMPACT + BATTERY BURST  ON A 2-STORY COMMERCIAL BUILDING
$#
$#   solver : LS-DYNA (Ansys Student / LS-DYNA Student)  explicit, SMP""",
    """$#=============================================================================
$# DRONE HIGH-SPEED IMPACT + BATTERY BURST  ON A 2-STORY COMMERCIAL BUILDING
$#
$#   ***  OPENRADIOSS VARIANT - GENERATED BY make_openradioss.py  ***
$#   ***  edit main.k, then re-run make_openradioss.py            ***
$#
$#   solver : OpenRadioss (free, no licence)  explicit, SMP""", "header")

sub("""$#   run    : lsdyna i=main.k ncpu=4 memory=200m""",
    """$#   run    : starter_win64.exe -i main_openradioss.k -np 4
$#            engine_win64.exe  -i main_openradioss_0001.rad -np 4""", "run line")

sub("""Drone impact and battery burst - 2 story retail building""",
    """Drone impact and battery burst - 2 story retail building - OpenRadioss""", "title")

# ------------------------------------------------------------ no blast.k ----
sub("""*INCLUDE
blast.inc
""", "$# blast.inc is NOT included here - OpenRadioss cannot map the blast\n"
     "$# keywords.  The burst is applied at the bottom of this file instead.\n",
    "blast include")

# ------------------------------------------------------- battery material ----
sub("""*MAT_CRUSHABLE_FOAM_TITLE
LiPo battery pack (crushable cell stack)
$# mid,ro,e,pr,lcid,tsc,damp
205,2.00E-6,1.0,0.0,205,0.005,0.10""",
    """*MAT_PIECEWISE_LINEAR_PLASTICITY_TITLE
LiPo battery pack (soft crushable stand-in for MAT_063)
205,2.00E-6,1.0,0.10,0.008,0.020,0.60,0.0
0.0,0.0,0,0,0.0
$# eps1..eps8
0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
$# es1..es8
0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0""", "battery material")

sub("""*DEFINE_CURVE_TITLE
Battery crush : yield stress [GPa] vs volumetric strain
$# lcid,sidr,sfa,sfo,offa,offo,dattyp
205,0,1.0,1.0,0.0,0.0,0
0.00,0.008
0.10,0.010
0.30,0.015
0.50,0.030
0.70,0.100
0.90,0.400
$
""", "", "battery curve")

# --------------------------------------------------------------- glazing ----
sub("""*MAT_ELASTIC_TITLE
Laminated glass 1F
$# mid,ro,e,pr,da,db,k
106,2.50E-6,70.0,0.22
$
*MAT_ELASTIC_TITLE
Laminated glass 2F
107,2.50E-6,70.0,0.22
$
*MAT_ADD_EROSION_TITLE
Glass 1F brittle fracture
$# mid,excl,mxpres,mneps,effeps,voleps,numfip,ncs
106,0.0,0.0,0.0,0.0,0.0,1.0,1.0
$# mnpres,sigp1,sigvm,mxeps,epssh,sigth,impulse,failtm
0.0,0.060,0.0,0.0020,0.0,0.0,0.0,0.0
$
*MAT_ADD_EROSION_TITLE
Glass 2F brittle fracture
107,0.0,0.0,0.0,0.0,0.0,1.0,1.0
0.0,0.060,0.0,0.0020,0.0,0.0,0.0,0.0""",
    """$# brittle glass as MAT_024: yields at 60 MPa and is deleted almost
$# immediately afterwards (FAIL = 0.0005 plastic strain), which reproduces
$# the shatter without relying on the *MAT_ADD_EROSION stress criterion.
*MAT_PIECEWISE_LINEAR_PLASTICITY_TITLE
Laminated glass 1F (brittle)
106,2.50E-6,70.0,0.22,0.060,0.0,0.0005,0.0
0.0,0.0,0,0,0.0
$# eps1..eps8
0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
$# es1..es8
0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
$
*MAT_PIECEWISE_LINEAR_PLASTICITY_TITLE
Laminated glass 2F (brittle)
107,2.50E-6,70.0,0.22,0.060,0.0,0.0005,0.0
0.0,0.0,0,0,0.0
$# eps1..eps8
0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
$# es1..es8
0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0""", "glazing")

# ----------------------------------------------------------- burst pulse ----
old_alt = src[src.index("$#-----------------------------------------------------------------------------\n$# ALTERNATIVE BURST MODEL"):src.index("*END")]
new_alt = """$#-----------------------------------------------------------------------------
$# BATTERY BURST - pressure pulse on the drone body shells (*LOAD_SHELL_SET
$# maps to Radioss /PLOAD).  Shell set 210 is generated into drone.k.
$#
$# Sizing: body shell area ~144,000 mm^2, body mass 0.335 kg.  A triangular
$# pulse of 8.0E-4 GPa over 0.5 ms carries an impulse of about 29 kg.mm/ms,
$# so the panels separate at roughly 85 m/s.  Pressure acts opposite to the
$# shell normal and the body normals point outward, hence the negative sign.
$#-----------------------------------------------------------------------------
*LOAD_SHELL_SET
$# esid,lcid,sf,at
210,90,1.0,0.0
$
*DEFINE_CURVE_TITLE
Battery burst pressure [GPa] vs time [ms]
$# lcid,sidr,sfa,sfo,offa,offo,dattyp
90,0,1.0,1.0,0.0,0.0,0
0.0,0.0
6.95,0.0
7.05,-8.0E-4
7.25,-4.0E-4
7.55,0.0
1000.0,0.0
$
"""
src = src.replace(old_alt, new_alt, 1)

out = os.path.join(HERE, "main_openradioss.k")
open(out, "w").write(src)
print("wrote", out, "(%d lines)" % src.count("\n"))
